-- Question 1
-- What is the total revenue generated by Dunder Mifflin Paper Company per month, ordered by highest to lowest revenue?

-- extracting the month

SELECT purchased_at,
       EXTRACT(MONTH FROM purchased_at) AS month, --float
       SUBSTR(purchased_at::varchar,6,2) AS month_worst_way --string
FROM tutorial.dunder_mifflin_paper_sales

-- creating a new column with the calculation of the row revenue, replacing the null values to zero

SELECT sub.*,
       ((price - discount_new) * quantity - shipping_cost_new) AS revenue
FROM (
      SELECT price,
             COALESCE(discount, 0) AS discount_new,
             quantity,
             COALESCE(shipping_cost, 0) AS shipping_cost_new
      FROM tutorial.dunder_mifflin_paper_sales
     ) sub

-- another way of subquering

WITH sub AS 
      (
      SELECT price,
             COALESCE(discount, 0) AS discount_new,
             quantity,
             COALESCE(shipping_cost, 0) AS shipping_cost_new
      FROM tutorial.dunder_mifflin_paper_sales
      )
SELECT sub.*,
       ((price - discount_new) * quantity - shipping_cost_new) AS revenue
FROM sub

-- now getting the answer: revenue per month
WITH sub AS 
      (
      SELECT EXTRACT(MONTH FROM purchased_at) AS month,
             price,
             COALESCE(discount, 0) AS discount_new,
             quantity,
             COALESCE(shipping_cost, 0) AS shipping_cost_new
      FROM tutorial.dunder_mifflin_paper_sales
      WHERE status = 'COMPLETED'
      )
SELECT month,
       SUM(((price - discount_new) * quantity - shipping_cost_new)) AS revenue
FROM sub
GROUP BY month
ORDER BY revenue DESC

-- image 1


-- Question 2
-- How many orders have been cancelled and what is the percentage of cancelled orders?

-- two ways of doing it:
-- #1
SELECT COUNT(cancelled_at) AS cancelled_orders,
       COUNT(order_id) AS total_orders,
       (COUNT(cancelled_at)/COUNT(order_id)::numeric) AS percentage_cancelled
FROM tutorial.dunder_mifflin_paper_sales

-- #2
SELECT SUM(CASE WHEN cancelled_at IS NOT NULL THEN 1 ELSE 0 END) AS cancelled_orders,
       COUNT(*) AS total_orders,
       (SUM(CASE WHEN cancelled_at IS NOT NULL THEN 1 ELSE 0 END) / COUNT(*)::numeric) * 100 AS percentage_cancelled
FROM tutorial.dunder_mifflin_paper_sales

-- image 2

-- Question 3
-- Which products have the highest average rating?

SELECT product_id,
       product_name,
       AVG(rating) AS average_rating
FROM tutorial.dunder_mifflin_paper_sales
WHERE rating IS NOT NULL
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 1

-- image 3

-- Question 4
-- What is the total shipping cost incurred by Dunder Mifflin Paper Company per region?

SELECT shipping_region,
       SUM(shipping_cost) AS shipping_cost
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY 1
ORDER BY 2 DESC

-- image 4

-- Question 5
-- Which account manager has generated the most revenue?

WITH sub AS 
      (
      SELECT account_manager,
             price,
             COALESCE(discount, 0) AS discount_new,
             quantity,
             COALESCE(shipping_cost, 0) AS shipping_cost_new
      FROM tutorial.dunder_mifflin_paper_sales
      WHERE status = 'COMPLETED'
      )
SELECT account_manager,
       SUM(((price - discount_new) * quantity - shipping_cost_new)) AS revenue
FROM sub
GROUP BY account_manager
ORDER BY revenue DESC
LIMIT 1

-- image 5

-- Question 6
-- What is the average quantity of products purchased per order (if the value is not an integer, round up to the value above)?

SELECT AVG(quantity) as avg_quantity
FROM tutorial.dunder_mifflin_paper_sales

SELECT CEILING(AVG(quantity)) AS avg_quantity
FROM tutorial.dunder_mifflin_paper_sales

-- image 6

-- Question 7
-- How many orders have been returned and what is the percentage of returned orders?

SELECT SUM(CASE WHEN returned_at IS NOT NULL THEN 1 ELSE 0 END) AS returned_orders,
       COUNT(*) AS total_orders,
       (SUM(CASE WHEN returned_at IS NOT NULL THEN 1 ELSE 0 END) / COUNT(*)::numeric) * 100 AS percentage_returned
FROM tutorial.dunder_mifflin_paper_sales

-- image 7

-- Question 8
-- Which product has the highest sales volume (quantity sold)? List the top 5.

SELECT product_id,
       SUM(quantity)
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5

-- image 8

-- Question 9
-- What is the average number of days it takes to ship an order per region?

SELECT shipping_region,
       AVG(days_to_ship) AS avg_days_to_ship
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY 1
ORDER BY 2 DESC

-- image 9

-- Question 10
-- Which city has the highest number of orders?

SELECT shipping_city,
       shipping_state,
       COUNT(order_id) AS number_of_orders
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY 1, 2
ORDER BY 3 DESC

-- all cities have 1 order each
-- image 10